In [1]:
import numpy as np

print("Numpy version:",np.__version__)

Numpy version: 2.4.6


In [ ]:
numbers = np.array([1,2,3,4,5])

print(numbers)
print(type(numbers))
print("shape:",numbers.shape) # 每个维度的长度
print("dtype:",numbers.dtype) # 元素的数据类型
print("ndim:",numbers.ndim)  # 数组有几个维度
print("size:",numbers.size) # 元素总数

[1 2 3 4 5]
<class 'numpy.ndarray'>
shape: (5,)
dtype: int64
ndim: 1
size: 5


In [4]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
])

print(matrix)
print("shape:",matrix.shape)
print("ndim:",matrix.ndim)
print("size:",matrix.size)

print(matrix[0,0])
print(matrix[0,2])
print(matrix[1,1])

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
size: 6
1
3
5


In [ ]:
integers = np.array([1,2,3])
floats = np.array([1.0,2.0,3.0])
booleans = np.array([True,False,True])
strings = np.array(["Python","Numpy","LLM"])

#dtype:查看数据类型，只读
print(integers.dtype)
print(floats.dtype)
print(booleans.dtype)
print(strings.dtype)

scores = np.array(
    [90,85,92],
    dtype=np.float32,
)

print(scores)
print(scores.dtype)

# astype:转换数据类型
integer_scores = scores.astype(np.int32)

print(integer_scores)
print(integer_scores.dtype)

int64
float64
bool
<U6
[90. 85. 92.]
float32
[90 85 92]
int32


In [7]:
zeros = np.zeros((2,3))
ones = np.ones((2,3))
full = np.full((2,3),7)
sequence = np.arange(0,10,2)
linear = np.linspace(0,1,5)

print("zeros:\n",zeros)
print("ones:\n",ones)
print("full:\n",full)
print("arange",sequence)
print("linspace",linear)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
full:
 [[7 7 7]
 [7 7 7]]
arange [0 2 4 6 8]
linspace [0.   0.25 0.5  0.75 1.  ]


In [8]:
numbers = np.array([10,20,30,40,50,60])

print(numbers[0])
print(numbers[-1])
print(numbers[:3])
print(numbers[2:5])
print(numbers[::2])
print(numbers[::-1])

10
60
[10 20 30]
[30 40 50]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
])

print(matrix[0])
print(matrix[:,1])
print(matrix[:2,:])
print(matrix[:2,2:]) 

[1 2 3 4]
[ 2  6 10]
[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]


In [11]:
original = np.array([1,2,3,4,5])
part = original[1:4]

print("修改前original:",original)
print("修改前part:",part)

part[0] = 999

print("修改后original:",original)
print("修改后part:",part)


修改前original: [1 2 3 4 5]
修改前part: [2 3 4]
修改后original: [  1 999   3   4   5]
修改后part: [999   3   4]


In [ ]:
numbers = np.arange(12)

print(numbers)
print(numbers.shape)

#matrix = numbers.reshape(3,4)
matrix = numbers.reshape(3,-1)

print(matrix)
print(matrix.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
