In [1]:
import numpy as np

print("Numpy version:",np.__version__)

Numpy version: 2.4.6


In [ ]:
numbers = np.array([1,2,3,4,5])

print(numbers)
print(type(numbers))
print("shape:",numbers.shape) # 每个维度的长度
print("dtype:",numbers.dtype) # 元素的数据类型
print("ndim:",numbers.ndim)  # 数组有几个维度
print("size:",numbers.size) # 元素总数

[1 2 3 4 5]
<class 'numpy.ndarray'>
shape: (5,)
dtype: int64
ndim: 1
size: 5


In [4]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
])

print(matrix)
print("shape:",matrix.shape)
print("ndim:",matrix.ndim)
print("size:",matrix.size)

print(matrix[0,0])
print(matrix[0,2])
print(matrix[1,1])

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
size: 6
1
3
5


In [ ]:
integers = np.array([1,2,3])
floats = np.array([1.0,2.0,3.0])
booleans = np.array([True,False,True])
strings = np.array(["Python","Numpy","LLM"])

#dtype:查看数据类型，只读
print(integers.dtype)
print(floats.dtype)
print(booleans.dtype)
print(strings.dtype)

scores = np.array(
    [90,85,92],
    dtype=np.float32,
)

print(scores)
print(scores.dtype)

# astype:转换数据类型
integer_scores = scores.astype(np.int32)

print(integer_scores)
print(integer_scores.dtype)

int64
float64
bool
<U6
[90. 85. 92.]
float32
[90 85 92]
int32


In [7]:
zeros = np.zeros((2,3))
ones = np.ones((2,3))
full = np.full((2,3),7)
sequence = np.arange(0,10,2)
linear = np.linspace(0,1,5)

print("zeros:\n",zeros)
print("ones:\n",ones)
print("full:\n",full)
print("arange",sequence)
print("linspace",linear)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
full:
 [[7 7 7]
 [7 7 7]]
arange [0 2 4 6 8]
linspace [0.   0.25 0.5  0.75 1.  ]


In [8]:
numbers = np.array([10,20,30,40,50,60])

print(numbers[0])
print(numbers[-1])
print(numbers[:3])
print(numbers[2:5])
print(numbers[::2])
print(numbers[::-1])

10
60
[10 20 30]
[30 40 50]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
])

print(matrix[0])
print(matrix[:,1])
print(matrix[:2,:])
print(matrix[:2,2:]) 

[1 2 3 4]
[ 2  6 10]
[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]


In [11]:
original = np.array([1,2,3,4,5])
part = original[1:4]

print("修改前original:",original)
print("修改前part:",part)

part[0] = 999

print("修改后original:",original)
print("修改后part:",part)


修改前original: [1 2 3 4 5]
修改前part: [2 3 4]
修改后original: [  1 999   3   4   5]
修改后part: [999   3   4]


In [18]:
numbers = np.arange(12)

print(numbers)
print(numbers.shape)

#matrix = numbers.reshape(3,4)
matrix = numbers.reshape(3,-1)

print(matrix)
print(matrix.shape)

# transpose 转置

x = np.arange(24).reshape(2,3,4)
print(x.shape)

y = x.transpose(1,0,2)
print(y.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
(2, 3, 4)
(3, 2, 4)


In [ ]:
# axis:沿哪个方向计算
matrix = np.array([
    [1,2,3],
    [4,5,6],
])
print(matrix.sum())
print(matrix.sum(axis=0)) #按列计算
print(matrix.sum(axis=1)) #按行计算

21
[5 7 9]
[ 6 15]


In [25]:
x = np.array([1,2,3])
print(x+10)

matrix = np.array([
    [1,2,3],
    [4,5,6],
])
bias = np.array([10,20,30])

result = matrix + bias

print(result)

mask = bias>15
print(mask)
print(bias[mask])
print(bias[bias>15])

mask2 = bias[(bias>15)&(bias<25)]
print(mask2)

[11 12 13]
[[11 22 33]
 [14 25 36]]
[False  True  True]
[20 30]
[20 30]
[20]


In [ ]:
import numpy as np

def cosine_similarity(a:np.ndarray,b:np.ndarray) -> float:
    dot_product = np.dot(a,b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)

    if norm_a == 0 or norm_b == 0:
        raise ValueError("zero vector has no cosine similarity")

    return float(dot_product / (norm_a * norm_b))



vector_a = np.array([1.0,2.0,3.0])
vector_b = np.array([1.0,2.0,3.0])
vector_c = np.array([-1.0,-2.0,-3.0])
vector_d = np.array([3.0,0.0,0.0])

print("a vs b:",cosine_similarity(vector_a,vector_b))
print("a vs c:",cosine_similarity(vector_a,vector_c))
print("a vs d:",cosine_similarity(vector_a,vector_d))

def normalize_vector(vector:np.ndarray) -> np.ndarray:
    norm = np.linalg.norm(vector)

    if norm == 0:
        raise ValueError("connot normalize a zero vector")

    return vector / norm

vector = np.array([3.0,4.0])
normalized = normalize_vector(vector)

print(vector)
print(normalized)
print(np.linalg.norm(normalized))


a vs b: 1.0
a vs c: -1.0
a vs d: 0.2672612419124244
[3. 4.]
[0.6 0.8]
1.0


In [ ]:
document_names = np.array([
    "document_a",
    "document_b",
    "document_c",
    "document_d",
])

top_k = 3
# argsort 返回按分数从小到大的索引（下标）
top_indices = np.argsort(scores)[::-1][:top_k]

print(top_indices)
print(document_names[top_indices])
print(scores[top_indices])

[2 0 1]
['document_c' 'document_a' 'document_b']
[92. 90. 85.]


In [30]:
rng = np.random.default_rng(42)

documents = rng.random((5,4))
query = rng.random(4)

scores = []
for doc_vec in documents:
    s = cosine_similarity(query,doc_vec)
    scores.append(s)

scores = np.array(scores)
print(scores)

[0.99145004 0.80973462 0.83863762 0.78155559 0.98110144]


In [31]:
import numpy as np

rng = np.random.default_rng(42)

documents = rng.random((10000,128))
query = rng.random(128)

print(documents.shape)
print(query.shape)

(10000, 128)
(128,)


In [39]:
import numpy as np

def cosine_loop(
        query:np.ndarray,
        documents:np.ndarray,
) ->np.ndarray:
    scores = []

    query_norm = np.linalg.norm(query)

    for document in documents:
        score = (
            np.dot(query,document)/(query_norm*np.linalg.norm(document))
        )

        scores.append(score)

    return np.array(scores)



scores_loop = cosine_loop(
    query,
    documents,
)

print(scores_loop.shape)

scores_vectorized = cosine_similarity_matrix(
    query,
    documents,
)
print(scores_vectorized.shape)
    

(10000,)


NameError: name 'cosine_similarity_matrix' is not defined